"""Generate notebook 05_model_comparison.ipynb"""
import json
from pathlib import Path


def make_notebook(cells):
    nb_cells = []
    for cell_type, source in cells:
        cell = {
            "cell_type": cell_type,
            "metadata": {},
            "source": source if isinstance(source, list) else [source],
        }
        if cell_type == "code":
            cell["execution_count"] = None
            cell["outputs"] = []
        nb_cells.append(cell)
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11.3"},
        },
        "cells": nb_cells,
    }


nb = make_notebook([
    ("markdown", [
        "# 05 — Model Comparison\n",
        "Compare PhenoAge baseline formula against ML algorithms for biological age prediction.\n",
        "\n",
        "**Target**: Minimize MAE (Mean Absolute Error) between predicted and chronological age.\n",
        "\n",
        "**Algorithms**:\n",
        "1. PhenoAge Formula (published baseline)\n",
        "2. ElasticNet Regression\n",
        "3. Ridge Regression\n",
        "4. Random Forest\n",
        "5. XGBoost\n",
        "6. LightGBM"
    ]),

    ("code", [
        "import sys, os\n",
        "sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '..', '..')))\n",
        "\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib\n",
        "matplotlib.use('Agg')\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "from sklearn.model_selection import KFold, cross_val_score\n",
        "from sklearn.linear_model import ElasticNet, Ridge, Lasso\n",
        "from sklearn.ensemble import RandomForestRegressor, StackingRegressor\n",
        "from sklearn.preprocessing import StandardScaler\n",
        "from sklearn.pipeline import Pipeline\n",
        "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score\n",
        "\n",
        "import xgboost as xgb\n",
        "import lightgbm as lgb\n",
        "\n",
        "sns.set_theme(style='whitegrid', font_scale=1.1)\n",
        "print('All libraries loaded.')"
    ]),

    ("markdown", ["## 1. Load clean data"]),
    ("code", [
        "df = pd.read_csv('../../data/processed/bioage_final_clean.csv')\n",
        "print(f'Clean data: {df.shape[0]} rows x {df.shape[1]} columns')\n",
        "print(f'Age range: {df.Age.min()} - {df.Age.max()}')\n",
        "df.head()"
    ]),

    ("markdown", ["## 2. Prepare features and target"]),
    ("code", [
        "# Features and target\n",
        "target = 'Age'\n",
        "feature_cols = [c for c in df.columns if c != target]\n",
        "\n",
        "X = df[feature_cols].values\n",
        "y = df[target].values\n",
        "\n",
        "print(f'Features: {feature_cols}')\n",
        "print(f'X shape: {X.shape}')\n",
        "print(f'y shape: {y.shape}')"
    ]),

    ("markdown", ["## 3. PhenoAge Baseline Formula"]),
    ("markdown", [
        "The PhenoAge formula from Levine et al. (2018) is a **two-step process**.\n",
        "Implementation adapted from [fangtiancheng/phenoage](https://github.com/fangtiancheng/phenoage).\n",
        "\n",
        "**Step 1**: Compute log-odds of 10-year mortality (note: **Chronological Age is an input feature**).\n",
        "```\n",
        "xb = -19.907 - 0.0336*ALB(g/L) + 0.0095*CRE(µmol/L) + 0.1953*GLU(mmol/L)\n",
        "     + 0.0954*ln(CRP/10) - 0.0120*LYMPH% + 0.0268*MCV\n",
        "     + 0.3306*RDW + 0.0019*ALP + 0.0554*WBC + 0.0804*Age\n",
        "```\n",
        "\n",
        "**Step 2**: Convert to biological age via Gompertz CDF.\n",
        "```\n",
        "gamma = 0.0076927\n",
        "M = 1 - exp(-exp(xb) * (exp(120*gamma) - 1) / gamma)\n",
        "PhenoAge = 141.50225 + ln(-0.00553 * ln(1 - M)) / 0.090165\n",
        "```"
    ]),
    ("code", [
        "# PhenoAge formula from Levine et al. 2018 (correct implementation)\n",
        "# Adapted from https://github.com/fangtiancheng/phenoage\n",
        "#\n",
        "# NOTE: NHANES units must be converted:\n",
        "#   LBXSAL (g/dL) -> g/L:   multiply by 10\n",
        "#   LBXSCR (mg/dL) -> µmol/L: multiply by 88.4\n",
        "#   LBXGLU (mg/dL) -> mmol/L: divide by 18\n",
        "#   CRP (mg/L) -> mg/dL: divide by 10, then take ln\n",
        "#   LBXWBCSI (1000 cells/uL) = 10^9/L (same unit)\n",
        "\n",
        "def phenoage_predict(row):\n",
        "    \"\"\"Apply the correct two-step PhenoAge formula.\"\"\"\n",
        "    # Unit conversions from NHANES to formula units\n",
        "    albumin = row['LBXSAL'] * 10          # g/dL -> g/L\n",
        "    creatinine = row['LBXSCR'] * 88.4     # mg/dL -> µmol/L\n",
        "    glucose = row['LBXGLU'] / 18.0        # mg/dL -> mmol/L\n",
        "    crp_log = np.log(row['CRP'] / 10.0)   # mg/L -> mg/dL -> ln\n",
        "    lymph = row['LBXLYPCT']               # %\n",
        "    mcv = row['LBXMCVSI']                 # fL\n",
        "    rdw = row['LBXRDW']                   # %\n",
        "    alp = row['LBXSAPSI']                 # U/L\n",
        "    wbc = row['LBXWBCSI']                 # 10^9/L\n",
        "    age = row['Age']                      # years (chronological age is an INPUT)\n",
        "\n",
        "    # Step 1: Compute log-odds mortality score\n",
        "    xb = (-19.907\n",
        "           - 0.0336 * albumin\n",
        "           + 0.0095 * creatinine\n",
        "           + 0.1953 * glucose\n",
        "           + 0.0954 * crp_log\n",
        "           - 0.0120 * lymph\n",
        "           + 0.0268 * mcv\n",
        "           + 0.3306 * rdw\n",
        "           + 0.0019 * alp\n",
        "           + 0.0554 * wbc\n",
        "           + 0.0804 * age)\n",
        "\n",
        "    # Step 2: Convert to biological age via Gompertz CDF\n",
        "    gamma = 0.0076927\n",
        "    M = 1.0 - np.exp(-np.exp(xb) * (np.exp(120 * gamma) - 1) / gamma)\n",
        "    M = np.clip(M, 1e-10, 1.0 - 1e-10)\n",
        "    bioage = 141.50225 + np.log(-0.00553 * np.log(1.0 - M)) / 0.090165\n",
        "    return bioage\n",
        "\n",
        "# Apply to all rows\n",
        "df['phenoage_pred'] = df.apply(phenoage_predict, axis=1)\n",
        "\n",
        "# Evaluate\n",
        "mae = mean_absolute_error(y, df['phenoage_pred'].values)\n",
        "rmse = np.sqrt(mean_squared_error(y, df['phenoage_pred'].values))\n",
        "r2 = r2_score(y, df['phenoage_pred'].values)\n",
        "\n",
        "print(f'PhenoAge Formula Results:')\n",
        "print(f'  MAE:  {mae:.3f} years')\n",
        "print(f'  RMSE: {rmse:.3f} years')\n",
        "print(f'  R²:   {r2:.4f}')"
    ]),

    ("markdown", ["## 4. Cross-Validation Setup"]),
    ("code", [
        "N_SPLITS = 5\n",
        "cv = KFold(n_splits=N_SPLITS, shuffle=True, random_state=42)\n",
        "print(f'{N_SPLITS}-fold cross-validation')\n",
        "print(f'Train size per fold: ~{int(len(X) * 0.8 / N_SPLITS)} samples')"
    ]),

    ("markdown", ["## 5. Algorithm Comparison"]),
    ("code", [
        "# Define models\n",
        "models = {\n",
        "    'ElasticNet': Pipeline([\n",
        "        ('scaler', StandardScaler()),\n",
        "        ('model', ElasticNet(alpha=0.1, l1_ratio=0.5, max_iter=10000))\n",
        "    ]),\n",
        "    'Ridge': Pipeline([\n",
        "        ('scaler', StandardScaler()),\n",
        "        ('model', Ridge(alpha=1.0))\n",
        "    ]),\n",
        "    'Random Forest': RandomForestRegressor(\n",
        "        n_estimators=200, max_depth=15, min_samples_leaf=10,\n",
        "        random_state=42, n_jobs=-1\n",
        "    ),\n",
        "    'XGBoost': xgb.XGBRegressor(\n",
        "        n_estimators=200, max_depth=6, learning_rate=0.1,\n",
        "        subsample=0.8, colsample_bytree=0.8,\n",
        "        random_state=42, verbosity=0\n",
        "    ),\n",
        "    'LightGBM': lgb.LGBMRegressor(\n",
        "        n_estimators=200, max_depth=8, learning_rate=0.1,\n",
        "        subsample=0.8, colsample_bytree=0.8,\n",
        "        random_state=42, verbose=-1\n",
        "    ),\n",
        "}\n",
        "\n",
        "print(f'Defined {len(models)} models for comparison.')"
    ]),

    ("code", [
        "# Cross-validate each model\n",
        "results = []\n",
        "\n",
        "# Add PhenoAge baseline\n",
        "pheno_mae = mean_absolute_error(y, df['phenoage_pred'].values)\n",
        "results.append({\n",
        "    'Model': 'PhenoAge Formula',\n",
        "    'MAE_mean': pheno_mae,\n",
        "    'MAE_std': 0,\n",
        "    'RMSE_mean': np.sqrt(mean_squared_error(y, df['phenoage_pred'].values)),\n",
        "    'R2_mean': r2_score(y, df['phenoage_pred'].values),\n",
        "})\n",
        "\n",
        "for name, model in models.items():\n",
        "    print(f'Training {name}...')\n",
        "    \n",
        "    # MAE scores\n",
        "    mae_scores = -cross_val_score(model, X, y, cv=cv, scoring='neg_mean_absolute_error', n_jobs=-1)\n",
        "    \n",
        "    # RMSE scores\n",
        "    rmse_scores = np.sqrt(-cross_val_score(model, X, y, cv=cv, scoring='neg_mean_squared_error', n_jobs=-1))\n",
        "    \n",
        "    # R2 scores\n",
        "    r2_scores = cross_val_score(model, X, y, cv=cv, scoring='r2', n_jobs=-1)\n",
        "    \n",
        "    results.append({\n",
        "        'Model': name,\n",
        "        'MAE_mean': mae_scores.mean(),\n",
        "        'MAE_std': mae_scores.std(),\n",
        "        'RMSE_mean': rmse_scores.mean(),\n",
        "        'R2_mean': r2_scores.mean(),\n",
        "    })\n",
        "    print(f'  MAE: {mae_scores.mean():.3f} +/- {mae_scores.std():.3f}')\n",
        "\n",
        "results_df = pd.DataFrame(results).sort_values('MAE_mean')\n",
        "print('\\n=== Results Summary ===')\n",
        "print(results_df.to_string(index=False))"
    ]),

    ("markdown", ["## 6. Results Visualization"]),
    ("code", [
        "fig, axes = plt.subplots(1, 3, figsize=(18, 6))\n",
        "\n",
        "# MAE comparison\n",
        "ax = axes[0]\n",
        "colors = ['#2ecc71' if m == results_df.Model.iloc[0] else '#3498db' for m in results_df.Model]\n",
        "bars = ax.barh(results_df.Model, results_df.MAE_mean, xerr=results_df.MAE_std, color=colors)\n",
        "ax.set_xlabel('MAE (years)')\n",
        "ax.set_title('Mean Absolute Error (lower = better)')\n",
        "ax.invert_yaxis()\n",
        "for bar, val in zip(bars, results_df.MAE_mean):\n",
        "    ax.text(bar.get_width() + 0.1, bar.get_y() + bar.get_height()/2, f'{val:.2f}', va='center')\n",
        "\n",
        "# RMSE comparison\n",
        "ax = axes[1]\n",
        "bars = ax.barh(results_df.Model, results_df.RMSE_mean, color=colors)\n",
        "ax.set_xlabel('RMSE (years)')\n",
        "ax.set_title('Root Mean Squared Error (lower = better)')\n",
        "ax.invert_yaxis()\n",
        "for bar, val in zip(bars, results_df.RMSE_mean):\n",
        "    ax.text(bar.get_width() + 0.1, bar.get_y() + bar.get_height()/2, f'{val:.2f}', va='center')\n",
        "\n",
        "# R2 comparison\n",
        "ax = axes[2]\n",
        "bars = ax.barh(results_df.Model, results_df.R2_mean, color=colors)\n",
        "ax.set_xlabel('R² Score')\n",
        "ax.set_title('R² Score (higher = better)')\n",
        "ax.invert_yaxis()\n",
        "for bar, val in zip(bars, results_df.R2_mean):\n",
        "    ax.text(bar.get_width() + 0.005, bar.get_y() + bar.get_height()/2, f'{val:.4f}', va='center')\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.savefig('../../reports/figures/14_model_comparison.png', dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
        "print('Saved: reports/figures/14_model_comparison.png')"
    ]),

    ("markdown", ["## 7. Best Model — Detailed Analysis"]),
    ("code", [
        "# Get best model\n",
        "best_row = results_df.iloc[0]\n",
        "best_name = best_row['Model']\n",
        "print(f'Best model: {best_name}')\n",
        "print(f'  MAE:  {best_row.MAE_mean:.3f} years')\n",
        "print(f'  RMSE: {best_row.RMSE_mean:.3f} years')\n",
        "print(f'  R²:   {best_row.R2_mean:.4f}')"
    ]),

    ("code", [
        "# Train best model on full data and show predictions\n",
        "if best_name in models:\n",
        "    best_model = models[best_name]\n",
        "else:\n",
        "    best_model = models['XGBoost']\n",
        "\n",
        "# Fit on full data for visualization\n",
        "best_model.fit(X, y)\n",
        "y_pred = best_model.predict(X)\n",
        "\n",
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
        "\n",
        "# Predicted vs Actual\n",
        "ax = axes[0]\n",
        "ax.scatter(y, y_pred, alpha=0.2, s=10)\n",
        "ax.plot([y.min(), y.max()], [y.min(), y.max()], 'r--', linewidth=2, label='Perfect prediction')\n",
        "ax.set_xlabel('Chronological Age')\n",
        "ax.set_ylabel('Predicted Biological Age')\n",
        "ax.set_title(f'{best_name}: Predicted vs Actual')\n",
        "ax.legend()\n",
        "\n",
        "# BioAge Gap distribution\n",
        "ax = axes[1]\n",
        "bioage_gap = y_pred - y\n",
        "ax.hist(bioage_gap, bins=50, edgecolor='white', alpha=0.8)\n",
        "ax.axvline(x=0, color='red', linestyle='--', linewidth=2)\n",
        "ax.set_xlabel('BioAge Gap (Predicted - Chronological)')\n",
        "ax.set_ylabel('Count')\n",
        "ax.set_title('BioAge Gap Distribution')\n",
        "ax.text(0.02, 0.95, f'Mean gap: {bioage_gap.mean():.2f} years\\nStd: {bioage_gap.std():.2f} years',\n",
        "        transform=ax.transAxes, va='top', fontsize=10,\n",
        "        bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.savefig('../../reports/figures/15_best_model_analysis.png', dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
        "print('Saved: reports/figures/15_best_model_analysis.png')"
    ]),

    ("markdown", ["## 8. Feature Importance (Tree-based models)"]),
    ("code", [
        "# Feature importance from best tree-based model\n",
        "if best_name in ['Random Forest', 'XGBoost', 'LightGBM']:\n",
        "    importances = best_model.feature_importances_\n",
        "else:\n",
        "    # Use XGBoost for feature importance\n",
        "    xgb_model = models['XGBoost']\n",
        "    xgb_model.fit(X, y)\n",
        "    importances = xgb_model.feature_importances_\n",
        "\n",
        "feat_imp = pd.DataFrame({\n",
        "    'Feature': feature_cols,\n",
        "    'Importance': importances\n",
        "}).sort_values('Importance', ascending=False)\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(8, 6))\n",
        "ax.barh(feat_imp.Feature, feat_imp.Importance, color='steelblue')\n",
        "ax.set_xlabel('Importance')\n",
        "ax.set_title('Feature Importance (XGBoost)')\n",
        "ax.invert_yaxis()\n",
        "plt.tight_layout()\n",
        "plt.savefig('../../reports/figures/16_feature_importance.png', dpi=150)\n",
        "plt.show()\n",
        "print('Saved: reports/figures/16_feature_importance.png')"
    ]),

    ("markdown", ["## 9. Final Summary"]),
    ("code", [
        "print('='*60)\n",
        "print('VITALAGE MODEL COMPARISON SUMMARY')\n",
        "print('='*60)\n",
        "print()\n",
        "print('Dataset: NHANES 2005-2023, Ages 18-80')\n",
        "print(f'Samples: {len(df)} | Features: {len(feature_cols)}')\n",
        "print()\n",
        "print('Results (5-fold CV):')\n",
        "print(results_df.to_string(index=False))\n",
        "print()\n",
        "print(f'Best Model: {best_name}')\n",
        "print(f'  MAE = {best_row.MAE_mean:.3f} +/- {best_row.MAE_std:.3f} years')\n",
        "print(f'  This means predictions are off by ~{best_row.MAE_mean:.1f} years on average.')\n",
        "print()\n",
        "if best_row.MAE_mean < 5:\n",
        "    print('VERDICT: Good model performance for a hackathon.')\n",
        "elif best_row.MAE_mean < 7:\n",
        "    print('VERDICT: Acceptable. Consider feature engineering or hyperparameter tuning.')\n",
        "else:\n",
        "    print('VERDICT: Needs improvement. Try adding more features or imputation.')"
    ]),

    ("markdown", [
        "## Next Steps\n",
        "1. Tune hyperparameters of the best model (GridSearchCV)\n",
        "2. Add interaction features (e.g., CRP × Albumin)\n",
        "3. Try imputation instead of complete-case to keep more rows\n",
        "4. Export the trained model as .pkl for the Streamlit app\n",
        "5. Compute BioAge Gap for each participant and analyze risk groups"
    ]),
])

Path("notebooks/blood/05_model_comparison.ipynb").write_text(
    json.dumps(nb, indent=1), encoding="utf-8"
)
print("Created 05_model_comparison.ipynb")
